import type { Metadata } from 'next'

/**
 * Per-couple layout. Exists only to wire the dynamic favicon — every
 * route under `/[template]/[slug]/...` (the public invitation AND the
 * dashboard) inherits the icon link declared here.
 *
 * The icon itself is generated by `app/[template]/[slug]/icon/route.ts`.
 */
export async function generateMetadata(
  { params }: { params: { template: string; slug: string } },
): Promise<Metadata> {
  return {
    icons: {
      icon: [{ url: `/${params.template}/${params.slug}/icon`, type: 'image/svg+xml' }],
    },
  }
}

export default function SlugLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
